### ISSUE TITLE
Syntax error on Float argument's default value

### ISSUE THREAD

**Issue by pavelhoral** [joelday/papyrus-lang#133] opened 2020-04-01 21:38 UTC
When a function has float argument with default value it is being reported as invalid syntax:

```
[fallout4]: Input string was not in a correct format.
(System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Single.Parse(String s)
   at DarkId.Papyrus.LanguageService.Program.Syntax.NodeBinder.<>c__DisplayClass38_0.<BindLiteralNode>b__2(FloatLiteralNode literalNode, Scanner`1 _) in C:\projects\papyrus-lang\src\DarkId.Papyrus.LanguageService\Program\Syntax\NodeBinder.cs:line 715
   at DarkId.Papyrus.LanguageService.Program.Syntax.NodeBinder.CreateNode[T](SyntaxNode parent, Scanner`1 parentChildren, Action`2 bindAction, Boolean ignoreExceptions) in C:\projects\papyrus-lang\src\DarkId.Papyrus.LanguageService\Program\Syntax\NodeBinder.cs:line 905)Papyrus
```

**To Reproduce**

Create the following empty script:
```
Scriptname Test extends Quest

Function Hello(Float afTest = 0.1)

EndFunction
```

![obrazek](https://user-images.githubusercontent.com/2012726/78189022-951c2e80-7471-11ea-9936-fdc1ed67a546.png)

**Comment by joelday** [comment] 2020-04-02 16:09
Thanks @pavelhoral, I'll get on this one as soon as I can.

**Comment by YeOldeDragon** [comment] 2020-08-01 00:30
Just to let you know...
I had this issue with float values and I realised it's caused by the OS Regional format config.
I live in Quebec, Canada, where the default float character is the comma `,` (don't ask me why...) so the `Number.ParseSingle` does not accept the dot `.` as a float character when running on this regional format.
I switched my region to English USA, restarted my project and all the parsing errors disappeared.

I'd fix the code by myself, but the papyrus-lang project doesn't compile "as is" on my PC and I don't have much time to look for what's missing.

Thanks for this great tool, modding would not be the same without it! :)

**Comment by pavelhoral** [comment] 2020-08-02 11:44
@YeOldeDragon Good catch. My OS's regional format is Czech and we too have comma as decimal separator.

**Comment by joelday** [comment] 2020-08-02 11:45
That would explain it! Thank you.

**Comment by joelday** [comment] 2020-08-09 01:06
@pavelhoral @YeOldeDragon This should be fixed now. Reopen if something bad happens. 🙂 Thanks!

**Closed by joelday** 2020-08-09 01:06 UTC
Labels: bug, good first issue
