### ISSUE TITLE
Autocomplete/Syntax not working with MO2 setup

### ISSUE THREAD

**Issue by Zapaeryan** [joelday/papyrus-lang#134] opened 2020-04-15 17:49 UTC
I've been trying to use this extension with MO2, but unfortunately my syntax and autocomplete seems really fucked up. it just isn't working properly (stuff like event and OnInit autocomplete to completely different stuff like "OghmaInfiniumScript", as if the program has it's priorities all fucked up) despite me having followed the installation instructions perfectly. I even tried running VS Code through MO2 with the right overwright folder set but that didn't work either. I vaguely remember it working properly, but that was with the files saved in my /Data folder and I haven't been able to replicate it since.

Can anyone tell me what's going on? Is this a bug on my end, or an issue with the current version? what can I do to fix this so my syntax is working properly with MO2?

**Comment by Tieantono** [comment] 2020-05-24 14:51
Yeah, me too, is there any specific instruction to use this extension seamlessly using MO2?

**Comment by Tieantono** [comment] 2020-05-24 17:03
Does the autocomplete literally not working at all or the issue you are facing is the order of the IntelliSense's suggestions? I've followed the instruction [here](https://github.com/joelday/papyrus-lang/wiki/Using-Mod-Organizer-2), and I also noticed that the generated Skyrim LE project file (`.ppj`) have incorrect directory path, which was `.\Source\Scripts` when it should be `.\Scripts\Source`.

This is the edited & working `.ppj` file:
![image](https://user-images.githubusercontent.com/14927392/82760033-29c05e80-9e1b-11ea-9ddc-57aa20b37cc0.png)

**Comment by joelday** [comment] 2023-09-27 18:29
Duplicate of #146

**Closed by joelday** 2023-09-27 18:29 UTC
